"""Fetch a curated set of Lucide icons and extract inner SVG content.

Lucide: ISC license, 24x24 viewBox, stroke-based, professionally designed.
We extract just the inner content (paths, circles, etc) so they can be rendered
inside our own <g transform=...> wrappers.

Outputs: _work/lucide_icons_extracted.py — a dict literal ready to paste in.
"""
import urllib.request
import re
import os
import json

BASE = 'https://unpkg.com/lucide-static@1.7.0/icons/'

# Curated mapping: concept_key -> lucide_icon_name
# Each concept gets a single Lucide icon chosen for best biological/evolutionary fit.
ICON_MAP = {
    # Anatomy / body parts
    'feather':    'feather',
    'wing':       'feather',         # Lucide has no 'wing'; feather is closest
    'leg':        'footprints',
    'foot':       'footprints',
    'hand':       'hand',
    'eye':        'eye',
    'bone':       'bone',
    'brain':      'brain',
    'skull':      'skull',
    # Organisms
    'bird':       'bird',
    'fish':       'fish',
    'rabbit':     'rabbit',
    'turtle':     'turtle',
    'worm':       'worm',
    'bug':        'bug',
    'cat':        'cat',
    'dog':        'dog',
    # Life & reproduction
    'egg':        'egg',
    'baby':       'baby',
    'sperm':      'fish',            # no sperm icon; use fish shape
    'heart':      'heart',
    'dna':        'dna',
    'microscope': 'microscope',
    # Plants
    'leaf':       'leaf',
    'tree':       'trees',
    'sprout':     'sprout',
    'flower':     'flower',
    # Environment
    'flame':      'flame',
    'drop':       'droplet',
    'sun':        'sun',
    'moon':       'moon',
    'cloud':      'cloud',
    'wind':       'wind',
    'snowflake':  'snowflake',
    'mountain':   'mountain',
    'peak':       'mountain',
    'waves':      'waves',
    # Abstract / mechanisms
    'atom':       'atom',
    'star':       'star',
    'bolt':       'zap',
    'check':      'check',
    'cross':      'x',
    'plus':       'plus',
    'minus':      'minus',
    'equal':      'equal',
    'percent':    'percent',
    'infinity':   'infinity',
    'repeat':     'repeat',
    'refresh':    'refresh-cw',
    'target':     'target',
    'compass':    'compass',
    'scale':      'scale',
    'trophy':     'trophy',
    'crown':      'crown',
    'shield':     'shield',
    'lock':       'lock',
    'key':        'key',
    'scissors':   'scissors',
    'flask':      'flask-conical',
    'test_tube':  'test-tube',
    'beaker':     'beaker',
    'pill':       'pill',
    'clock':      'clock',
    'hourglass':  'hourglass',
    'calendar':   'calendar',
    'arrow_r':    'arrow-right',
    'arrow_up':   'arrow-up',
    'arrow_down': 'arrow-down',
    'link':       'link',
    'globe':      'globe',
    'layers':     'layers',
    'network':    'network',
    'shuffle':    'shuffle',
    'merge':      'git-merge',
    'branch':     'git-branch',
    'fork':       'git-fork',
    # Additional biology-specific
    'footprints': 'footprints',
    'paw':        'paw-print',
    'shell':      'shell',
    'snail':      'snail',
    'gem':        'gem',
    'thermometer':'thermometer',
    'fuel':       'fuel',
}

# Clean up duplicate lucide names (we may have same lucide icon mapped to multiple keys)
unique_lucide = set(ICON_MAP.values())
print(f'Fetching {len(unique_lucide)} unique Lucide icons...')

cache = {}
for lucide_name in sorted(unique_lucide):
    url = BASE + lucide_name + '.svg'
    try:
        with urllib.request.urlopen(url, timeout=10) as r:
            svg_text = r.read().decode('utf-8')
        # Extract inner content (everything between opening <svg ...> and </svg>)
        m = re.search(r'<svg[^>]*>(.*?)</svg>', svg_text, re.DOTALL)
        if not m:
            print(f'  SKIP {lucide_name}: no svg content')
            continue
        inner = m.group(1).strip()
        # Strip the license comment if any
        inner = re.sub(r'<!--.*?-->', '', inner, flags=re.DOTALL).strip()
        # Collapse whitespace
        inner = re.sub(r'\s+', ' ', inner)
        cache[lucide_name] = inner
        print(f'  OK {lucide_name} ({len(inner)} bytes)')
    except Exception as e:
        print(f'  ERR {lucide_name}: {e}')

# Now build the final key -> inner dict using ICON_MAP
final = {}
for key, lucide_name in ICON_MAP.items():
    if lucide_name in cache:
        final[key] = cache[lucide_name]

out_path = '_work/lucide_icons_extracted.py'
with open(out_path, 'w', encoding='utf-8') as f:
    f.write('"""Lucide icon inner content — auto-generated by fetch_lucide_icons.py\n')
    f.write('ISC license: https://github.com/lucide-icons/lucide/blob/main/LICENSE\n')
    f.write('All icons: 24x24 viewBox, stroke-based.\n"""\n\n')
    f.write('LUCIDE_ICONS = {\n')
    for key in sorted(final.keys()):
        val = final[key].replace('"', '\\"')
        f.write(f'    {key!r}: "{val}",\n')
    f.write('}\n')

print(f'\nWrote {len(final)} icons to {out_path}')
print(f'File size: {os.path.getsize(out_path):,} bytes')
