#!/usr/bin/env python3
"""Generate ALL flashcards for Evolution Study Guide and inject into data.json"""
import json, os, copy

PROJ = r'C:\Users\johnn\Desktop\evolution-study-guide'
DATA = os.path.join(PROJ, 'data.json')

# ============================================================
# ALL FLASHCARDS — organized by node ID
# Each card: {"front": "question", "back": "answer with TECHNICAL + ELI5"}
# ============================================================

ALL_CARDS = {}

# ────────────────────────────────────────────────────────────
# NODE 1: lec1-intro-evolution
# ────────────────────────────────────────────────────────────
ALL_CARDS["lec1-intro-evolution"] = [
    {"front": "What is the most precise scientific definition of evolution?",
     "back": "**TECHNICAL:** Evolution is a change in the frequency of alleles in a population across generations. It occurs at the population level, NOT within an individual's lifetime, and is measured by tracking allele frequency shifts over time.\n\n**ELI5:** Imagine a bag of M&Ms where each color is a gene version. Evolution is when the mix of colors in the bag changes from one refill to the next — not when a single M&M changes color."},
    {"front": "Who said 'Nothing in biology makes sense except in the light of evolution,' and in what year?",
     "back": "**TECHNICAL:** Theodosius Dobzhansky, in a 1973 essay published in The American Biology Teacher. This statement encapsulates evolution's role as the central organizing principle of all biological sciences.\n\n**ELI5:** Dobzhansky (1973) basically said biology without evolution is like trying to understand a movie by watching random scenes — you need the storyline (evolution) to make sense of any of it."},
    {"front": "Why is evolution considered the unifying theory of biology?",
     "back": "**TECHNICAL:** Every subfield of biology — cell biology, ecology, genetics, anatomy, physiology — rests on the insight that organisms share common ancestry and have been shaped by natural selection, drift, mutation, and gene flow. Without evolution, shared molecular machinery (universal genetic code), homologous structures, and biodiversity patterns have no causal explanation.\n\n**ELI5:** Evolution is like gravity for biology — it's the one rule that explains everything. Why do humans and bananas share DNA? Why do bacteria become resistant to drugs? Why do whales have finger bones? Evolution is the answer to all of it."},
    {"front": "List five practical applications of evolutionary biology.",
     "back": "**TECHNICAL:** (1) Agriculture — crop breeding and understanding pest resistance. (2) Medicine — antibiotic design and predicting resistance evolution. (3) Conservation — managing genetic diversity in endangered populations. (4) Immunology — understanding pathogen adaptation and vaccine design. (5) Epidemiology — predicting outbreak evolution and tracking pathogen spread.\n\n**ELI5:** Evolution helps us grow better food, make better medicine, save endangered animals, understand how diseases spread, and design vaccines that actually work against shape-shifting viruses."},
    {"front": "What is the difference between a scientific theory and a guess or hypothesis?",
     "back": "**TECHNICAL:** A scientific theory is a well-substantiated explanation supported by multiple independent lines of evidence, tested repeatedly, and accepted by the scientific community. Evolution is on the same epistemic footing as the theory of gravitation, plate tectonics, and aerodynamics — not a speculation but a rigorously confirmed framework.\n\n**ELI5:** In everyday language, 'theory' means a guess. In science, a 'theory' is more like a GPS that's been tested a million times and always gets you to the right place. Evolution is that reliable."},
    {"front": "Why is it wrong to say 'organisms improve over time' when describing evolution?",
     "back": "**TECHNICAL:** Evolution is population-level change in allele frequencies, not improvement or progress toward some goal. There is no 'higher' or 'lower' — bacteria are as evolved as humans. Selection optimizes for the current environment, which can change, so today's 'improvement' may be tomorrow's disadvantage.\n\n**ELI5:** Evolution isn't a ladder going up — it's more like a bush growing in every direction. A cockroach isn't 'less evolved' than you; it's just evolved differently for its lifestyle. If anything, cockroaches have survived way longer than humans have existed."},
    {"front": "Why can't an individual organism evolve?",
     "back": "**TECHNICAL:** Evolution requires a change in allele frequencies across generations within a population. An individual's genotype is fixed at conception. While an individual can change phenotypically (e.g., gaining muscle), these somatic changes are not heritable and do not constitute evolution. Populations evolve; individuals do not.\n\n**ELI5:** You can't evolve any more than a single playing card can change the deck. Evolution is about the whole deck of cards changing its composition over many reshuffles (generations)."},
    {"front": "A student says: 'Giraffes evolved long necks because they stretched to reach tall trees.' What is wrong with this reasoning?",
     "back": "**TECHNICAL:** This is Lamarckian inheritance of acquired characteristics, which is incorrect. Stretching (a somatic/phenotypic change) does not alter germline DNA. The correct explanation: giraffes with genetically longer necks survived and reproduced more successfully (natural selection), passing those alleles to offspring. The population shifted toward longer necks over generations.\n\n**ELI5:** Working out at the gym doesn't give your kids bigger muscles. Giraffes didn't stretch into long necks — the ones born with longer necks got more food, survived better, had more babies, and those babies also had long necks. Repeat for thousands of generations."},
    {"front": "What does 'fitness' mean in evolutionary biology? How does it differ from everyday usage?",
     "back": "**TECHNICAL:** Fitness is the ability of an organism to survive and reproduce RELATIVE to other individuals in the same population. It is always comparative — not an absolute measure. A fit organism is one that leaves more copies of its alleles in the next generation than its competitors. It has nothing to do with strength or physical health.\n\n**ELI5:** In evolution, 'fit' doesn't mean buff or athletic. It means who has the most babies that survive. A scrawny mouse that has 20 babies is 'fitter' than a muscular mouse that has 2."},
    {"front": "What is an adaptation in evolutionary terms?",
     "back": "**TECHNICAL:** An adaptation is a heritable trait that increases an organism's fitness relative to individuals lacking that trait, within a specific environment. Adaptations arise through natural selection acting on heritable phenotypic variation over generations.\n\n**ELI5:** An adaptation is like a cheat code that helps you win the survival game — but only in a specific level. A polar bear's thick fur is a great adaptation in the Arctic, but it would be terrible in the Sahara."},
    {"front": "What is the CHANGE mnemonic for evolution?",
     "back": "**TECHNICAL:** CHANGE = Change in allele frequencies over generations — the minimal, most precise definition of evolution from a population genetics perspective.\n\n**ELI5:** Evolution = CHANGE in the gene recipe book of a whole population, one generation at a time."},
    {"front": "In what year was On the Origin of Species published, and by whom?",
     "back": "**TECHNICAL:** On the Origin of Species was published by Charles Darwin in 1859. It presented the theory of evolution by natural selection with extensive evidence from biogeography, comparative anatomy, embryology, and artificial selection.\n\n**ELI5:** Darwin dropped the biggest science bomb of the 1800s in 1859 — a book that basically said 'all life is related and nature picks winners.' It changed biology forever."},
]

# ────────────────────────────────────────────────────────────
# NODE 2: lec1-flu-case-study
# ────────────────────────────────────────────────────────────
ALL_CARDS["lec1-flu-case-study"] = [
    {"front": "What are the two key surface proteins on the influenza virus, and what does each do?",
     "back": "**TECHNICAL:** (1) Hemagglutinin (HA) — binds the virus to host cell surface receptors, enabling entry. (2) Neuraminidase (NA) — cleaves sialic acid bonds, allowing newly assembled virus particles to detach from the host cell and spread to new cells.\n\n**ELI5:** HA is the key that unlocks the door to get INTO your cells. NA is the scissors that cut the rope so new viruses can ESCAPE and infect more cells. Together they're the flu's breaking-and-entering toolkit."},
    {"front": "How many genes and RNA segments does influenza have?",
     "back": "**TECHNICAL:** Influenza has 13 genes distributed across 8 separate RNA segments. This segmented genome is crucial because it enables reassortment — the exchange of entire segments between different strains during co-infection.\n\n**ELI5:** The flu's instruction manual comes in 8 separate booklets (not one big book). If two different flu strains infect the same cell, their booklets can get mixed up, creating a totally new flu combo. That's why pandemics happen."},
    {"front": "What is antigenic drift?",
     "back": "**TECHNICAL:** Antigenic drift is the gradual accumulation of point mutations (amino acid substitutions) in the HA and NA surface proteins due to error-prone RNA replication. These small changes progressively reduce vaccine effectiveness and allow the virus to partially escape host immunity.\n\n**ELI5:** Imagine the flu is a criminal who gets a tiny nose job every year. Each year the police sketch (your immune system's memory) matches a little less. Eventually the disguise is good enough to sneak past your defenses — that's why you need a new flu shot every year."},
    {"front": "What is antigenic shift (reassortment), and how does it differ from antigenic drift?",
     "back": "**TECHNICAL:** Antigenic shift occurs when two different influenza strains co-infect a single host cell and exchange entire RNA segments, producing a novel reassortant virus with a dramatically different HA or NA surface protein. Unlike drift (gradual, small mutations), shift is sudden and can produce pandemic strains because the population has no pre-existing immunity.\n\n**ELI5:** Drift is like slowly changing your outfit piece by piece. Shift is like two people swapping entire wardrobes — suddenly you look completely different. That's why shift causes pandemics: nobody's immune system recognizes the new look."},
    {"front": "How did the 2009 H1N1 pandemic strain originate?",
     "back": "**TECHNICAL:** H1N1 (2009) arose by triple reassortment — it combined RNA segments from avian (bird), swine (pig), and human influenza strains in a single pig host. Pigs serve as 'mixing vessels' because their respiratory cells have receptors for both avian and human flu strains.\n\n**ELI5:** A pig caught bird flu and human flu at the same time. Inside the pig, the viruses shuffled their gene booklets together like a deck of cards, creating a brand-new flu that nobody had seen before. That new flu jumped to humans and became the 2009 pandemic."},
    {"front": "Describe the Hensley et al. (2009, Science) experiment and what it demonstrated.",
     "back": "**TECHNICAL:** Hensley et al. passaged influenza virus through vaccinated mice for 9 successive infection cycles. The virus evolved altered HA proteins (vaccine escape mutations). In contrast, virus passaged through unvaccinated control mice showed NO HA changes. This directly demonstrated that selection imposed by host immunity drives HA evolution — proof that vaccine-escape is an evolutionary response, not random.\n\n**ELI5:** Scientists played a game of 'tag' with flu and vaccinated mice for 9 rounds. The flu that kept getting caught by the immune system changed its disguise. The flu playing against unvaccinated mice (no immune system challenge) didn't bother changing at all. This proved the vaccine was the selection pressure forcing the virus to evolve."},
    {"front": "Why does influenza require an annual vaccine update?",
     "back": "**TECHNICAL:** Because HA and NA surface proteins continually accumulate amino acid substitutions via antigenic drift (error-prone RNA replication + immune selection). Within 1-2 years, the circulating strains diverge enough from last year's vaccine strain that the vaccine's antibodies no longer bind effectively. WHO surveillance tracks global strains to predict which variants to include each season.\n\n**ELI5:** The flu changes its 'face' every year through tiny mutations. Last year's vaccine trained your immune system to recognize last year's face. This year's flu looks different enough to sneak past. So scientists have to update the 'wanted poster' (vaccine) every year."},
    {"front": "Why do most influenza mutations NOT lead to vaccine escape?",
     "back": "**TECHNICAL:** Most mutations are neutral or slightly deleterious. Only rare mutations that alter the HA/NA epitopes recognized by antibodies — while still maintaining protein function — provide a selective advantage. The vast majority of mutations either don't affect antigenicity or break the protein's function.\n\n**ELI5:** Most disguise changes the flu tries actually make it worse — like putting on a mask that also blocks its own eyes. Only a few lucky changes help it hide from your immune system AND still work properly. Those rare winners are what spread."},
    {"front": "Why are pigs considered 'mixing vessels' for influenza evolution?",
     "back": "**TECHNICAL:** Pig respiratory epithelial cells express receptors for both avian-type (alpha-2,3-linked sialic acid) and human-type (alpha-2,6-linked) influenza strains. This allows co-infection by bird and human strains, enabling reassortment of RNA segments and the emergence of novel pandemic strains.\n\n**ELI5:** Pigs are like a blender that can mix bird flu and human flu together. Their cells have 'doors' that both bird and human viruses can use, so if a pig catches both at once, the viruses can swap parts and create something totally new."},
    {"front": "How does influenza demonstrate that evolution is observable in real time?",
     "back": "**TECHNICAL:** Influenza's high mutation rate (error-prone RNA replication), short generation time (hours), and large population sizes allow evolution to be directly observed within a single flu season. Genomic surveillance can track the emergence, spread, and fixation of adaptive mutations in HA/NA across the global population in real time.\n\n**ELI5:** Evolution usually takes thousands of years, but the flu evolves so fast we can literally watch it happen season by season. It's like watching a time-lapse of evolution — new versions pop up, spread, and take over within months."},
    {"front": "What is the HA-NA mnemonic?",
     "back": "**TECHNICAL:** HA-NA = HemAgglutinin and NeurAminidase — the two most rapidly evolving surface proteins on influenza, the primary targets of immune selection and vaccines. H and N numbers (e.g., H1N1, H3N2) classify flu subtypes by these proteins.\n\n**ELI5:** Think of HA as the 'Hook' (it hooks onto your cells) and NA as the 'Nibbler' (it nibbles the virus free). These two are what flu vaccines target, and what the flu keeps changing."},
]

# ────────────────────────────────────────────────────────────
# NODE 3: lec1-takehome-course
# ────────────────────────────────────────────────────────────
ALL_CARDS["lec1-takehome-course"] = [
    {"front": "Why is evolution considered a predictive science? Give a specific example.",
     "back": "**TECHNICAL:** Evolutionary theory predicts that pathogens will evolve resistance under selection, that populations will diverge when isolated, and that shared ancestry will produce molecular homologies. Flu surveillance directly demonstrates prediction: monitoring pig farms is evolutionarily motivated because pigs serve as mixing vessels for reassortment — predicting where novel pandemic strains are most likely to emerge.\n\n**ELI5:** Evolution isn't just about the past — it tells us what's coming. Scientists monitor pig farms because evolution predicts pigs will be the blenders where new flu strains are born. That's like having a weather forecast for pandemics."},
    {"front": "Why do epidemiologists monitor pig farms for novel flu strains?",
     "back": "**TECHNICAL:** Pigs express both avian and human influenza receptors, allowing co-infection and reassortment. Evolutionary theory predicts that pig farms — with high animal density and exposure to both avian and human strains — are the most likely sites for novel pandemic strain emergence.\n\n**ELI5:** Pig farms are like virus mixing bowls. Pigs can catch bird flu AND human flu at the same time, and the viruses can swap parts inside the pig. Scientists watch pig farms because that's where the next pandemic flu is most likely to be cooked up."},
    {"front": "What is the textbook for BIOL 4230?",
     "back": "**TECHNICAL:** Evolution: Making Sense of Life (2nd Edition).\n\n**ELI5:** The class textbook is 'Evolution: Making Sense of Life' — second edition."},
    {"front": "What is Dr. Travis Robbins' research focus?",
     "back": "**TECHNICAL:** Dr. Robbins studies the ecology and evolution of lizards, particularly the genus Sceloporus. His work focuses on reptile physiology, life history evolution, and thermal adaptation.\n\n**ELI5:** Dr. Robbins is a lizard scientist. He studies how lizards evolve to handle different temperatures and environments — basically how lizards play the survival game."},
    {"front": "What does BIOL 4230 expect beyond passive memorization?",
     "back": "**TECHNICAL:** The course emphasizes active learning: reading assigned material before class, attending lectures, and applying concepts to novel problems. Passive memorization of definitions is insufficient — students must understand mechanisms, make predictions, and analyze data.\n\n**ELI5:** You can't just memorize flashcards and pass this class (ironic, I know). You need to actually understand the 'why' and 'how' well enough to apply concepts to problems you've never seen before."},
]

# ────────────────────────────────────────────────────────────
# NODE 4: lec2-pre-darwin
# ────────────────────────────────────────────────────────────
ALL_CARDS["lec2-pre-darwin"] = [
    {"front": "What was the 'Great Chain of Being' and what did it assume about species?",
     "back": "**TECHNICAL:** The Great Chain of Being was the dominant Western framework from Ancient Greek philosophy through the 18th century. It arranged all organisms in a fixed, divinely ordained hierarchy from 'lower' (minerals, plants) to 'higher' (humans, angels, God). Species were considered immutable — they did not change over time.\n\n**ELI5:** People used to think every species was like a rung on a permanent ladder set up by God — plants at the bottom, humans near the top, and nothing ever moved. No evolution, no change, everything in its assigned spot forever."},
    {"front": "What did Archbishop Ussher calculate, and when?",
     "back": "**TECHNICAL:** In 1664, Archbishop James Ussher used biblical chronology to calculate that Creation occurred on October 23, 4004 BC, at 9:00 AM. This placed Earth's age at roughly 6,000 years — far too short for evolution by natural selection.\n\n**ELI5:** A church leader in 1664 added up all the ages in the Bible and declared Earth was created on a specific Tuesday morning in 4004 BC. That's like saying the Earth is younger than some bristlecone pine trees (which are over 4,000 years old)."},
    {"front": "What was Linnaeus's contribution to biology? (dates: 1707-1778)",
     "back": "**TECHNICAL:** Carl Linnaeus developed binomial nomenclature (genus + species naming) and hierarchical classification (kingdom, class, order, genus, species). He organized biodiversity under a presumed Divine Plan but unknowingly created a framework that later revealed evolutionary relationships.\n\n**ELI5:** Linnaeus was biology's librarian — he invented the system for giving every organism a two-part name (like Homo sapiens) and organizing them into groups. He thought he was cataloging God's creations, but his filing system accidentally showed how life is related through evolution."},
    {"front": "What was Buffon's contribution to evolutionary thinking? (1707-1788)",
     "back": "**TECHNICAL:** Georges-Louis Leclerc, Comte de Buffon, proposed that organisms could be transformed by 'organic particles' and argued that Earth was much older than Ussher's 6,000 years. He challenged the idea of species fixity but did not propose a mechanism of change.\n\n**ELI5:** Buffon said 'Hey, maybe Earth is actually really old and animals can change.' He didn't figure out HOW they change, but he opened the door that Darwin later walked through."},
    {"front": "What is uniformitarianism, and who proposed it?",
     "back": "**TECHNICAL:** Uniformitarianism, proposed by James Hutton (1726-1797) and later championed by Charles Lyell, holds that the geological processes we observe today (erosion, sedimentation, volcanic activity) have operated at roughly the same rates throughout Earth's history. This implies Earth must be extremely old — far older than Ussher's estimate — to produce the geological features we observe.\n\n**ELI5:** Hutton looked at canyons and mountains and said 'The same slow processes we see today — rivers eroding, volcanoes building — carved these landscapes. That means Earth must be REALLY old.' It's like seeing a tiny stream and realizing it carved the Grand Canyon given enough time."},
    {"front": "What did Cuvier contribute to pre-Darwinian science? (1769-1832)",
     "back": "**TECHNICAL:** Georges Cuvier was a paleontologist who documented EXTINCTION using the fossil record — proving that species could disappear entirely, which challenged the Great Chain of Being. He proposed catastrophism: that sudden geological events (floods, volcanic eruptions) caused mass extinctions, which were followed by new creations.\n\n**ELI5:** Cuvier found bones of animals that don't exist anymore and proved extinction is real. Before him, people thought God made everything permanent. He said 'Nope, stuff goes extinct' — but he thought it was from big disasters, not evolution."},
    {"front": "Who proposed the first formal theory of evolution, and why was the mechanism wrong?",
     "back": "**TECHNICAL:** Jean-Baptiste Lamarck (1744-1829) proposed the first formal theory of evolution. His mechanism was inheritance of acquired characteristics — the idea that organisms change during their lifetime through use/disuse and pass these changes to offspring (e.g., a blacksmith's children inherit stronger arms). This is wrong because somatic changes do not alter germline DNA.\n\n**ELI5:** Lamarck was right that species change over time (evolution), but wrong about HOW. He thought if you worked out a lot, your kids would be born buff. That's like thinking if you dye your hair blue, your baby will have blue hair. Changes to your body don't rewrite your DNA."},
    {"front": "Why was William Smith (1769-1839) important for understanding geological time?",
     "back": "**TECHNICAL:** William Smith organized geological history by fossil content — demonstrating that specific fossils are associated with specific rock strata (faunal succession). This allowed geologists to correlate rock layers across different locations and establish a relative timeline of Earth's history.\n\n**ELI5:** Smith figured out that certain fossils always appear in certain rock layers — like how if you're digging through old yearbooks, the fashion tells you the decade. He used fossils as timestamps for rocks."},
    {"front": "How did Lyell influence Darwin's thinking?",
     "back": "**TECHNICAL:** Charles Lyell's Principles of Geology, which Darwin read aboard the Beagle, argued for uniformitarianism and an Earth old enough for gradual geological change. This gave Darwin the conceptual framework for biological change over vast timescales — if mountains can be built grain by grain, species can be modified generation by generation.\n\n**ELI5:** Lyell showed Darwin that Earth is crazy old and that tiny changes add up to huge results over millions of years. Darwin thought 'If rivers can carve canyons slowly, maybe nature can sculpt new species slowly too.'"},
    {"front": "Place these pre-Darwin figures in chronological order: Cuvier, Darwin, Lamarck, Linnaeus, Lyell.",
     "back": "**TECHNICAL:** Linnaeus (1707-1778) → Lamarck (1744-1829) → Cuvier (1769-1832) → Lyell (1797-1875) → Darwin (1809-1882). The mnemonic LCLLL captures the sequence: Linnaeus (classification) → Cuvier (extinction) → Lamarck (first mechanism) → Lyell (deep time) → Darwin (natural selection).\n\n**ELI5:** Think of it like a relay race where each runner hands off an idea to the next: Linnaeus sorted life → Cuvier proved things go extinct → Lamarck said life changes → Lyell showed Earth is old enough → Darwin figured out HOW."},
    {"front": "Why was it important that extinction was documented before Darwin proposed natural selection?",
     "back": "**TECHNICAL:** If species are permanent and divinely fixed (Great Chain of Being), there is no room for evolution. Cuvier's documentation of extinction proved species CAN disappear, challenging fixity. Combined with Hutton and Lyell's deep time, this created the intellectual space for Darwin's mechanism — species are not permanent, and there is enough time for gradual change.\n\n**ELI5:** Before you can argue that species change into new ones, you first have to prove they're NOT permanent. Cuvier showed the universe deletes species. Hutton/Lyell showed there's enough time for new ones to appear. Darwin put it all together."},
]

# ────────────────────────────────────────────────────────────
# NODE 5: lec2-darwin-voyage
# ────────────────────────────────────────────────────────────
ALL_CARDS["lec2-darwin-voyage"] = [
    {"front": "How old was Darwin when he joined the HMS Beagle, and what were the voyage dates?",
     "back": "**TECHNICAL:** Darwin was 22 years old when he joined the HMS Beagle as the ship's naturalist. The voyage lasted from 1831 to 1836 — a 5-year circumnavigation primarily along the coast of South America and through the Galápagos Islands.\n\n**ELI5:** Darwin was basically a college-aged kid (22) who got on a boat for 5 years and came back with ideas that changed the world. He left in 1831 and returned in 1836."},
    {"front": "What role did John Gould play in Darwin's thinking about evolution?",
     "back": "**TECHNICAL:** John Gould was the London ornithologist who examined Darwin's Galápagos bird specimens and identified them as all FINCHES — different species adapted to different ecological niches. Darwin had not realized this in the field. Gould's identification was the catalytic insight that led Darwin to recognize adaptive divergence from a common ancestor.\n\n**ELI5:** Darwin collected birds from different Galápagos islands thinking they were totally different types. When he got home, bird expert John Gould said 'Dude, these are ALL finches — just modified versions.' That was Darwin's 'aha!' moment."},
    {"front": "What did the fossil and living armadillos in South America suggest to Darwin?",
     "back": "**TECHNICAL:** Darwin found fossil armadillos (glyptodonts) that resembled living armadillos in the same geographic region. This geographic correspondence — extinct and living forms being similar in the same location — suggested descent with modification: the living species descended from the fossil forms.\n\n**ELI5:** Darwin found ancient armadillo fossils near where modern armadillos live. It was like finding your great-great-grandmother's photo and realizing you look a lot like her. The old ones turned into the new ones over time."},
    {"front": "Why did Darwin wait over 20 years before publishing On the Origin of Species?",
     "back": "**TECHNICAL:** Darwin was a meticulous scientist who wanted overwhelming evidence before presenting a controversial theory. He spent decades collecting supporting data from barnacle taxonomy, pigeon breeding, plant hybridization, biogeography, and correspondence with other naturalists. He also feared the social and religious backlash his theory would provoke.\n\n**ELI5:** Darwin knew his idea was a bombshell and didn't want to drop it until he had bulletproof evidence. He spent 20+ years building his case like a lawyer preparing for the trial of the century. He was also scared of getting roasted by the church."},
    {"front": "Who independently arrived at the theory of natural selection, and what happened?",
     "back": "**TECHNICAL:** Alfred Russel Wallace independently conceived of natural selection while studying in the Malay Archipelago. He sent Darwin a letter describing his theory in 1858. Their ideas were presented jointly at the Linnean Society of London in 1858 — a presentation that went largely unnoticed at the time. Darwin then rushed to publish Origin of Species in 1859.\n\n**ELI5:** Wallace basically came up with the same idea as Darwin, independently, and sent Darwin a letter about it. Darwin panicked ('He's going to scoop me!'), so they presented together in 1858 at a science meeting. Nobody really noticed. Then Darwin published his book in 1859 and became famous."},
    {"front": "What book did Darwin read during the Beagle voyage that heavily influenced his thinking?",
     "back": "**TECHNICAL:** Darwin read Charles Lyell's Principles of Geology during the voyage. Lyell's uniformitarianism — the idea that slow, ongoing geological processes explain Earth's features over vast timescales — provided Darwin with the framework of deep time necessary for gradual biological change.\n\n**ELI5:** Darwin read a geology book by Lyell on the ship that said 'tiny changes + tons of time = huge results.' Darwin applied that same logic to living things: tiny differences + tons of generations = new species."},
    {"front": "What is the 'Beagle→Book' mnemonic?",
     "back": "**TECHNICAL:** Beagle→Book: 5 years voyage (1831-36) + 23 years thinking = Origin of Species (1859). This captures the remarkable gap between Darwin's key observations and his eventual publication.\n\n**ELI5:** The voyage took 5 years, the thinking took 23 years, and then the book dropped in 1859. Darwin was the ultimate procrastinator — but for good reason."},
    {"front": "What key geological evidence did Darwin observe during the Beagle voyage?",
     "back": "**TECHNICAL:** Darwin observed the uplift of the Andes Mountains and the formation of volcanic islands, providing firsthand evidence for Lyell's uniformitarianism and deep time. These geological observations convinced him that Earth was old enough for gradual biological change.\n\n**ELI5:** Darwin saw mountains being pushed up and volcanic islands being born in real time. If the Earth itself could be slowly reshaped, maybe species could be slowly reshaped too."},
]

# ────────────────────────────────────────────────────────────
# NODE 6: lec2-natural-selection-ingredients
# ────────────────────────────────────────────────────────────
ALL_CARDS["lec2-natural-selection-ingredients"] = [
    {"front": "What are the five necessary ingredients for evolution by natural selection?",
     "back": "**TECHNICAL:** (1) High reproductive potential — organisms produce more offspring than can survive. (2) Population size remains roughly stable — resources constrain growth. (3) Resources are limited → struggle for existence. (4) Phenotypic variation among individuals. (5) Heritability of that variation. INFERENCE: Survival and reproduction are therefore NONRANDOM with respect to phenotype.\n\n**ELI5:** More babies are born than can survive (1,2,3), they're all a little different (4), and kids look like their parents (5). Put it together: the ones with the best traits for their environment survive and pass those traits on."},
    {"front": "Who was Thomas Malthus, and how did he influence Darwin?",
     "back": "**TECHNICAL:** Thomas Malthus (1766-1834) was an economist who observed that populations reproduce exponentially while resources grow arithmetically, creating inevitable competition. Darwin read Malthus and recognized that this 'struggle for existence' creates the selective pressure that drives natural selection.\n\n**ELI5:** Malthus said 'People have babies way faster than farms grow food, so there's always competition.' Darwin read this and thought 'That's true for ALL species — and the winners of that competition shape evolution!'"},
    {"front": "Give three extreme examples of reproductive potential mentioned in class.",
     "back": "**TECHNICAL:** (1) Aphids could produce 524 billion offspring in 1 year. (2) A single pair of elephants could produce 19 million descendants in 750 years. (3) Staphylococcus bacteria would cover Earth 7 feet deep in just 24 hours if unconstrained. None of these happen because resources limit growth.\n\n**ELI5:** If nothing died and food was unlimited, aphids would bury the planet in a year, bacteria would drown us in a day, and elephants would overrun everything in a few centuries. The fact that this DOESN'T happen proves there's a constant survival competition."},
    {"front": "What happens if ANY of the five ingredients of natural selection is missing?",
     "back": "**TECHNICAL:** If any ingredient is absent, natural selection cannot operate: (1) No overproduction → no competition. (2) Unlimited resources → no differential survival. (3) No variation → selection has nothing to act on. (4) No heritability → favorable traits are not passed on, so no cumulative change. All five must be present simultaneously.\n\n**ELI5:** Natural selection is like a recipe — leave out any ingredient and the cake doesn't rise. No variation = nothing to choose from. No heritability = winners can't pass on their advantage. You need ALL five or evolution by natural selection stops."},
    {"front": "Natural selection acts on ________, but evolution is measured as changes in ________.",
     "back": "**TECHNICAL:** Natural selection acts on PHENOTYPES (observable traits that determine survival and reproduction), but evolution is measured as changes in ALLELE FREQUENCIES at the genotype level. Selection 'sees' phenotypes but the evolutionary record is written in genotypes.\n\n**ELI5:** Nature judges you by your looks and abilities (phenotype), but the scoreboard tracks your DNA (genotype). A bird with a bigger beak survives the drought (phenotype selected), but evolution is measured by whether the 'big beak' gene became more common (allele frequency change)."},
    {"front": "What is the difference between fitness and adaptation?",
     "back": "**TECHNICAL:** FITNESS = the ability to survive and reproduce RELATIVE to others in the population. It is a comparative, population-level measure. ADAPTATION = a specific heritable trait that increases fitness relative to individuals without it. Fitness is the outcome; adaptation is the trait that contributes to that outcome.\n\n**ELI5:** Fitness is your overall score in the survival game. Adaptation is a specific power-up that helps you get a higher score. A cheetah's speed (adaptation) contributes to its overall survival success (fitness)."},
    {"front": "Why can't sunburn evolve via natural selection?",
     "back": "**TECHNICAL:** Sunburn is a non-heritable phenotypic change — it is an environmental effect on the individual, not encoded in germline DNA. Since it fails the heritability requirement, natural selection cannot act on sunburn to produce evolutionary change. Only heritable variation can be passed to offspring.\n\n**ELI5:** Your sunburn doesn't change your DNA, so your kids won't be born pre-tanned. Evolution needs changes that get passed down — a tan doesn't qualify."},
    {"front": "What is the VHI-DRS mnemonic?",
     "back": "**TECHNICAL:** VHI-DRS = Variation + Heritability + Inference from Differential Reproductive Success = Evolution by natural selection. These are the essential components Darwin identified.\n\n**ELI5:** To remember what makes natural selection work: Variation (things are different), Heritability (parents pass traits to kids), and the best variants have more babies (Differential Reproductive Success)."},
]

print(f"Generating cards... (writing first batch of {sum(len(v) for v in ALL_CARDS.values())} cards)")

# Continue in next part...
# Save what we have so far as a checkpoint
with open(os.path.join(PROJ, '_work', 'cards_checkpoint.json'), 'w', encoding='utf-8') as f:
    json.dump(ALL_CARDS, f, ensure_ascii=False, indent=1)
print(f"Checkpoint saved: {sum(len(v) for v in ALL_CARDS.values())} cards across {len(ALL_CARDS)} nodes")
