"""Build content/flashcards.js from lecture-guides key_terms.
   Merges hand-crafted application examples from flashcard-examples.json.
   Each lecture becomes a deck; an "all" deck contains every card."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "public"
GUIDES_DIR = ROOT / "data" / "lecture-guides"
META = ROOT / "data" / "evol4230.json"
EXAMPLES_FILE = ROOT / "data" / "flashcard-examples.json"
OUT_FILE = ROOT / "content" / "flashcards.js"

meta = json.loads(META.read_text(encoding="utf-8"))
lecture_titles = {L["id"]: L["title"] for L in meta["lectures"]}

# Load examples (term -> scenario)
examples = {}
if EXAMPLES_FILE.exists():
    raw = json.loads(EXAMPLES_FILE.read_text(encoding="utf-8"))
    for lid, lec_examples in raw.items():
        if lid.startswith("_"):
            continue
        if not isinstance(lec_examples, dict):
            continue
        examples.setdefault(lid, {}).update(lec_examples)

decks = {}
labels = {}
all_cards = []
missing = []

for fp in sorted(GUIDES_DIR.glob("L*.json")):
    lid = fp.stem
    g = json.loads(fp.read_text(encoding="utf-8"))
    cards = []
    for s in g.get("sections", []):
        for kt in s.get("key_terms", []):
            term = (kt.get("term") or "").strip()
            definition = (kt.get("def") or "").strip()
            if not term or not definition:
                continue
            example = examples.get(lid, {}).get(term, "")
            if not example:
                missing.append(f"{lid} :: {term}")
            cards.append({
                "term": term,
                "def": definition,
                "example": example,
                "ctx": f"{lid} §{s.get('letter','')} — {s.get('title','')}",
            })
    if cards:
        decks[lid] = cards
        labels[lid] = f"{lid} — {lecture_titles.get(lid, lid)}"
        all_cards.extend(cards)

decks["all"] = all_cards
labels["all"] = f"All lectures ({len(all_cards)} cards)"

js_body = (
    "/* Auto-generated by scripts-v2/build-flashcards.py from lecture-guides key_terms.\n"
    f"   {len(all_cards)} cards across {len(decks) - 1} lectures + 'all' deck.\n"
    f"   Each card includes term/def/example. */\n"
    f"window.FLASHCARD_DECKS = {json.dumps(decks, ensure_ascii=False, indent=0)};\n"
    f"window.FLASHCARD_LABELS = {json.dumps(labels, ensure_ascii=False, indent=0)};\n"
    f"window.FC_DECKS = {json.dumps(list(decks.keys()), ensure_ascii=False)};\n"
    "console.log('[flashcards loaded]', Object.keys(window.FLASHCARD_DECKS).length, 'decks,', "
    "Object.values(window.FLASHCARD_DECKS).reduce((s, d) => s + d.length, 0), 'cards total');\n"
)
OUT_FILE.write_text(js_body, encoding="utf-8")
print(f"Wrote {OUT_FILE}")
print(f"  {len(decks) - 1} per-lecture decks + 'all' deck")
print(f"  {len(all_cards)} total cards")
with_example = sum(1 for c in all_cards if c["example"])
print(f"  {with_example} cards have an example ({with_example * 100 // len(all_cards)}%)")
if missing:
    print(f"\n  MISSING examples ({len(missing)}):")
    for m in missing[:20]:
        print(f"    - {m}")
    if len(missing) > 20:
        print(f"    ... and {len(missing) - 20} more")
