"""Merge data/stim-bank/L*.json files into content/stim-bank.js.
Builds an index by exam, lecture, topic for fast UI lookup.
"""
import json
from pathlib import Path
from collections import defaultdict

ROOT = Path(__file__).resolve().parent.parent / "public"
SRC_DIR = ROOT / "data" / "stim-bank"
OUT = ROOT / "content" / "stim-bank.js"

def main():
    questions = []
    for fp in sorted(SRC_DIR.glob("L*.json")):
        try:
            data = json.loads(fp.read_text(encoding="utf-8"))
            if isinstance(data, list):
                questions.extend(data)
            elif isinstance(data, dict) and isinstance(data.get("questions"), list):
                questions.extend(data["questions"])
            else:
                print(f"  ! {fp.name} unrecognized shape, skipping")
        except json.JSONDecodeError as e:
            print(f"  ! {fp.name} invalid JSON: {e}")

    questions.sort(key=lambda q: q.get("id", ""))

    by_exam = defaultdict(list)
    by_lecture = defaultdict(list)
    by_topic = defaultdict(list)
    for q in questions:
        by_exam[q.get("exam")].append(q["id"])
        by_lecture[q.get("lecture")].append(q["id"])
        by_topic[q.get("topic", "")].append(q["id"])

    index = {
        "byExam":    {str(k): v for k, v in sorted(by_exam.items(), key=lambda kv: (kv[0] is None, kv[0]))},
        "byLecture": dict(sorted(by_lecture.items())),
        "byTopic":   dict(sorted(by_topic.items())),
    }

    body = (
        "/* Auto-generated by scripts-v2/merge-stim-bank.py — do not edit by hand. */\n"
        f"window.STIM_BANK = {json.dumps(questions, ensure_ascii=False, indent=0)};\n"
        f"window.STIM_INDEX = {json.dumps(index, ensure_ascii=False, indent=0)};\n"
        "console.log('[stim-bank loaded]', window.STIM_BANK.length, 'questions');\n"
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    print(f"Wrote {OUT} — {len(questions)} questions")
    print(f"  by exam: {dict((k, len(v)) for k, v in by_exam.items())}")
    print(f"  by lecture: {len(by_lecture)} lectures, range {min(len(v) for v in by_lecture.values()) if by_lecture else 0}-{max(len(v) for v in by_lecture.values()) if by_lecture else 0}")

if __name__ == "__main__":
    main()
