"""Enrich every flashcard in content-final.js with:
 - analogy: common, relatable comparison for the concept
 - hint: word-origin / mnemonic / obvious-point observation
Then append cards for any uncovered section.
"""
import json, re, sys, os
sys.stdout.reconfigure(encoding='utf-8')
PUB = r'C:\Users\johnn\Desktop\School\Evolution_EVOL4230\evolution-study-guide\public'
CF = os.path.join(PUB, 'js', 'content-final.js')
raw = open(CF, encoding='utf-8').read()
start = raw.index('window.COURSE = ') + len('window.COURSE = ')
data = json.loads(raw[start:].rstrip().rstrip(';').rstrip())

# (keywords, analogy, hint)
LIB = [
    (['monophyletic','monophyly'],
     'Like taking a whole branch off a tree — cut includes the ancestor and every descendant.',
     'mono = one; phyly = tribe. ONE tribe = the WHOLE group sharing an ancestor.'),
    (['paraphyletic','paraphyly'],
     'Like "reptiles excluding birds" — a branch with one twig pointedly left out. Incomplete.',
     'para = beside/alongside → group is BESIDE the full group, missing a piece.'),
    (['polyphyletic'],
     'Grouping "warm-blooded animals" (birds + mammals) — same trait, different branches. Convergence, not kinship.',
     'poly = many. Many separate origins lumped by looks, not by ancestry.'),
    (['homolog','homology','homologous'],
     'Your arm and a whale flipper — same bones, different jobs. Same blueprint, different house.',
     'homo = same, logy = relation. SAME origin — regardless of current function.'),
    (['analog','analogous','convergent evolution','convergent'],
     'Dolphin and shark — same streamlined job, totally different builders. Two chefs inventing pizza alone.',
     'ana- = counter/parallel. SAME function from DIFFERENT origins.'),
    (['deep homology','pax6','master gene'],
     'Same Lego set, different models — Pax6 makes "eye" in flies and mice despite wildly different eyes.',
     'Pax6 = pax ("box") + 6 → the 6th identified "box" gene. Ancient, conserved master-switch for eye.'),
    (['cladogram','phylogenetic tree','tree of life'],
     'A family tree — tips = alive today, nodes = common ancestors.',
     'clade = branch. Read like an upside-down tree: time flows from root (old) to tips (now).'),
    (['last common ancestor','lca'],
     'You and your cousin share Grandma — the LCA. Everyone on a branch shares its base.',
     'LCA lives AT the node — it is not any living species you can point to today.'),
    (['parsimony'],
     "Occam's razor for trees: fewest trait-changes explanation is usually right.",
     'parsimony = "frugal." The SIMPLEST tree (fewest steps) beats a flashier one.'),
    (['molecular clock'],
     'DNA ticks at roughly steady rate — count mutations, get an age. Like candle burn-time.',
     'Clock = rate. Works because most mutations are neutral → accumulate like steady ticking.'),
    (['radiometric','half-life','carbon-14','c-14','k-ar','potassium-argon','u-pb'],
     'Half-life = wait time for half the popcorn to pop. Rate known + amount left → elapsed time.',
     'Half-life NEVER changes with temperature or pressure. Pick the isotope with a half-life matching your sample age.'),
    (['cambrian'],
     'The Cambrian explosion is evolution\'s Renaissance — body-plan diversity shot up fast.',
     'Cambrian = ~541 mya. Most major animal phyla appeared in ~20 My — blink in geological time.'),
    (['mass extinction','big five','k-pg','k-t','permian'],
     'Jenga tower after too many pieces pulled — ecosystem collapses. 5 times in Earth\'s history.',
     'Big Five: Ordovician, Devonian, Permian (worst — 96% marine species), Triassic, K-Pg (dinos).'),
    (['fossil'],
     'A fossil is a biological photograph pressed into stone — we see a biased fragment of the past.',
     'Most organisms NEVER fossilize. Hard parts in sediment = overrepresented; soft bodies = rare.'),
    (['biological species concept','reproductive isolation'],
     'Can two breeds meet and make fertile puppies? If yes, same species. If sterile (mule), isolated.',
     'BSC applies only to SEXUAL species. No good for asexuals or extinct fossils.'),
    (['allopatric','geographic isolation'],
     'Friends moved to different towns → different slang → eventually can\'t hang out at all.',
     'allo = other; patric = place. OTHER PLACE → isolated by geography.'),
    (['sympatric'],
     'Roommates stop talking in the same house — colocated, but socially isolated.',
     'sym = same; patric = place. SAME PLACE → speciation WITHOUT geography.'),
    (['hybrid','hybridization'],
     'A mule (donkey × horse) — alive, strong, but sterile. Nature\'s "doesn\'t combine."',
     'Hybrid sterility = postzygotic. F1 may live; F2 may be sickly → "hybrid breakdown."'),
    (['reinforcement'],
     'Populations hybridize poorly → selection doubles down on "don\'t mate with them." Like couples counseling for species.',
     'Reinforcement = selection AGAINST hybridization, strengthening prezygotic isolation.'),
    (['ring species'],
     'Ring of friends, each neighbor chats, but ring-ends can\'t talk to each other. Speciation caught in-progress.',
     'Classic: Ensatina salamanders around California\'s Central Valley.'),
    (['natural selection'],
     'Like a sieve: environment filters which alleles pass to the next generation.',
     'Needs 3 ingredients: variation, heritability, differential reproduction. Miss any → no evolution.'),
    (['sexual selection'],
     'Peacock\'s tail — useless for survival, gold for dating. Mate choice drives burden traits.',
     'Intrasexual = males fighting males (antlers). Intersexual = females choosing (tails).'),
    (['hardy-weinberg','hardy weinberg','hwe'],
     'A calm pond — no wind, no rocks, no drain. Allele frequencies stay still. Ripple = evolution.',
     'HWE holds only if: no selection, no mutation, no migration, no drift, random mating. Break ANY → evolution.'),
    (['genetic drift','drift'],
     'Coin flips in a small crowd get noisy fast — random allele change, small populations feel it most.',
     'Drift effect ∝ 1/N. BIG population = drift is tiny. SMALL population = drift dominates.'),
    (['bottleneck'],
     'Cheetahs squeezed through a genetic needle — crash wipes out variation. Survivors ≠ representative sample.',
     'Bottleneck ≠ founder. Bottleneck = population CRASHES; founder = SMALL group LEAVES to start new pop.'),
    (['founder effect','founder'],
     'A few colonists move to a new island — their rare alleles become "common" by accident.',
     'Founder = drift on arrival. "Who happened to move" shapes the new gene pool.'),
    (['gene flow','migration'],
     'Students transfer between schools and swap slang — gene flow mixes populations, keeps them similar.',
     'Gene flow OPPOSES speciation. More migration = populations converge, not diverge.'),
    (['mutation'],
     'Typos in DNA photocopying — usually harmless, rarely brilliant, occasionally catastrophic.',
     'Mutations are RANDOM w.r.t. fitness. Selection is what\'s non-random. Mutation ≠ adaptation.'),
    (['heritability','breeder'],
     'h² = how much of trait variance comes from genes vs environment. 0 = all learned, 1 = all DNA.',
     'R = h² × S. No h², no response to selection. Breeder\'s equation: "how fast does this evolve?"'),
    (['quantitative trait','polygenic'],
     'Many genes each nudging a ruler — result is a bell curve, not categories.',
     'Quantitative = CONTINUOUS trait (height, weight). Mendelian = DISCRETE (flower color).'),
    (['fitness'],
     'Fitness = number of offspring reaching reproductive age. Not strongest, not smartest — most fertile.',
     'Fitness is ALWAYS relative to other genotypes in the SAME environment. Change environment → fitness changes.'),
    (['adaptation'],
     'A trait shaped by selection to do a job — like a screwdriver evolved from a general stick.',
     'Adaptation = trait + FUNCTION + SELECTION history. Not every useful feature is an adaptation.'),
    (['allele'],
     'Two recipes for the same cake (gene) — vanilla and chocolate are alleles.',
     'allele comes from Greek allelon = "of one another." Alternative forms of the same gene.'),
    (['genotype'],
     'The recipe written in your DNA.',
     'geno = gene; type = kind. The genetic makeup, not what you see.'),
    (['phenotype'],
     'The cake that came out of the oven (genotype + baking conditions).',
     'pheno = "to show." What SHOWS in the organism.'),
    (['phenotypic plasticity','plasticity'],
     'Same seeds, different soil → different plants. Same genotype, different phenotype depending on conditions.',
     'Plasticity is NOT evolution — it\'s within-lifetime flexibility. Doesn\'t pass to offspring unless genes change.'),
    (['inbreeding'],
     'Cousin-marriages stack recessive diseases. Inbreeding depression = fewer reshuffled alleles.',
     'Inbreeding INCREASES homozygosity. Rare recessive alleles get exposed when both copies match.'),
    (['heterozygosity','heterozygote'],
     'Carrying two different alleles — like having both a key and a lockpick.',
     'heteros = different. HeteroZYGOUS = two different alleles at one locus.'),
    (['coevolution','arms race','red queen'],
     'Red Queen: run just to stay in place. Host-parasite, predator-prey — everyone evolving to not fall behind.',
     'Red Queen from Alice: "It takes all the running you can do, to keep in the same place."'),
    (['batesian','mimic'],
     'Harmless fly wears wasp costume — scares predators for free. Works when real wasps are around.',
     'Named after H. W. Bates. One species MIMICS a DANGEROUS model. Parasitic on the model.'),
    (['müllerian','mullerian'],
     'Wasps and bees share yellow-black — predators learn once, avoid all. Shared advertising.',
     'Named after Fritz Müller. BOTH mimics are genuinely dangerous. Mutualistic.'),
    (['life history','r-selected','r-selection','r-strategist'],
     'r-selected = many cheap kids (fish). Boom-bust environments favor quantity.',
     'r = intrinsic rate of increase. High r = many young, little care, unstable environments.'),
    (['k-selected','k-selection','k-strategist'],
     'K-selected = few premium kids (elephants). Stable environments favor quality.',
     'K = carrying capacity. Low r, high parental care, stable populations at equilibrium.'),
    (['aging','senescence'],
     'Aging = genes helping young-you sneak past selection even while hurting old-you.',
     'Antagonistic pleiotropy: same gene boosts youth fitness, costs late life. Selection is weak after reproduction.'),
    (['trade-off','tradeoff'],
     'Can\'t be huge + fast + fertile + long-lived — energy budget forces you to pick.',
     'Trade-offs are WHY perfect organisms don\'t exist. Every gain has a cost.'),
    (['kin selection','hamilton'],
     '"Die for 2 brothers or 8 cousins" — Haldane. Genes help copies of themselves even in other bodies.',
     "Hamilton's rule: rB > C. r=relatedness, B=benefit to recipient, C=cost to actor."),
    (['altruism','altruistic'],
     'Bee gives life for hive — pays in shared genes. Only evolves if recipient shares your DNA.',
     'True altruism = cost to self, benefit to OTHER. Must be explained by kin selection or reciprocity.'),
    (['ess','evolutionarily stable','game theory'],
     'ESS = stable poker strategy. If everyone plays it, no one wins more by switching.',
     'Not necessarily OPTIMAL — just UNINVADABLE. Classic: hawk-dove equilibrium.'),
    (['hox','homeobox'],
     'Hox genes = body\'s zoning laws: "head here, legs here." Small edits reshape whole organisms.',
     'Hox order on chromosome MIRRORS body axis — colinearity. Ancient and conserved across animals.'),
    (['heterochrony'],
     'Development on a different clock. Axolotls staying juvenile = neoteny.',
     'heteros + chronos = different + time. CHANGE IN TIMING of developmental events.'),
    (['evo-devo','evolution of development'],
     'Same Lego bricks, new models. Tweak developmental genes → huge morphological shifts.',
     'Evo-devo shows that MACROevolution can come from small gene-regulation changes, not just many mutations.'),
    (['bipedal','lucy','australopithecus'],
     'Lucy walked upright 3.2 mya — bipedalism came BEFORE big brains in our lineage.',
     'Lucy = Australopithecus afarensis, Ethiopia, 1974. Named after "Lucy in the Sky with Diamonds."'),
    (['hominin'],
     'Hominin = humans + all close extinct relatives (Neanderthals, Australopithecus). Narrow.',
     'Hominin ≠ hominid. Hominid = great apes + humans. Hominin = humans + extinct close relatives only.'),
    (['neanderthal'],
     'Neanderthals buried their dead, made tools; ~1-4% of your DNA is theirs.',
     'Named after Neander Valley (Germany). Went extinct ~40 kya, but we interbred first.'),
    (['out of africa','out-of-africa'],
     'Modern humans: African origin ~200,000 ya, global spread ~50-60 kya. Your ancestors had African accents.',
     'Evidence: highest genetic diversity in Africa + fossil sequence. Supports single origin over multiregional.'),
    (['antibiotic resistance','antibiotic'],
     'Antibiotic use is training the enemy — kill the weak, hand an open city to the resistant.',
     'Resistance alleles exist BEFORE drug exposure (rare). Antibiotic just selects for them — doesn\'t create them.'),
    (['mismatch','stone age'],
     'Mismatch: bodies evolved for scarcity, environment now has abundance. Obesity + diabetes = evolution\'s revenge.',
     'Mismatch hypothesis: ancestral environment ≠ modern environment → maladaptation to the NEW world.'),
    (['vestigial'],
     'Appendix, goosebumps, wisdom teeth — evolutionary leftovers. Old app icons you never open.',
     'Vestigial doesn\'t mean USELESS — just REDUCED from an ancestral role. Some still have minor functions.'),
    (['sickle cell'],
     'Sickle-cell: one copy = malaria protection, two copies = disease. Heterozygote advantage.',
     'Classic balancing selection: allele harmful in homozygote, BENEFICIAL in heterozygote → stays at moderate frequency.'),
    (['heterozygote advantage','overdominance'],
     'Like sickle-cell in malaria zones — mixing two alleles beats having two of the same.',
     'Overdominance = heterozygote (Aa) fitness > either homozygote (AA or aa). Maintains polymorphism.'),
    (['darwin','wallace'],
     'Darwin and Wallace independently arrived at natural selection. Ideas whose time had come.',
     'Wallace\'s 1858 letter from Indonesia forced Darwin to publish. They co-presented at the Linnean Society.'),
    (['lamarck'],
     'Lamarck thought giraffes stretched necks to pass on longer necks — wrong mechanism, right question.',
     'Lamarck: INHERITANCE OF ACQUIRED CHARACTERISTICS. Falsified — somatic changes don\'t reach germline.'),
    (['mendel','pea','punnett'],
     'Mendel\'s peas: traits inherit as discrete units, not blended paint. 3:1, 9:3:3:1 — genetics\' cheat codes.',
     'Mendel published 1866, ignored until 1900 rediscovery. "Fathered" genetics in a monastery garden.'),
    (['synthesis','modern synthesis','neo-darwin'],
     '1940s fusion of Darwin + Mendel + population genetics = Modern Synthesis. Evolution got its math.',
     'Key players: Dobzhansky, Mayr, Simpson, Huxley. "Nothing in biology makes sense except in light of evolution."'),
    (['biogeograph'],
     'Biogeography = nature\'s postal zones. Why kangaroos are in Australia, not Canada.',
     'Historical biogeography = PAST movements. Ecological biogeography = CURRENT distributions.'),
    (['continental drift','plate tectonics'],
     'Continents on slow puzzle pieces — what\'s apart was once joined. Explains matching fossils across oceans.',
     'Wegener (1912) proposed, dismissed; confirmed in 1960s by seafloor spreading evidence. Pangaea ~250 mya.'),
    (['island biogeograph'],
     'Big + close = most species. Small + far = fewest. Real-estate law for biodiversity.',
     'MacArthur-Wilson model: S = f(area, isolation). Used today for nature-reserve design.'),
    (['endemic'],
     'Endemic = "only found here" — lemurs to Madagascar, giant tortoises to Galápagos.',
     'High endemism signals LONG ISOLATION. Oceanic islands breed endemics.'),
    (['adaptive radiation'],
     'One ancestor, many descendant forms, fast. Galápagos finches and Hawaiian honeycreepers are classic.',
     'Trigger: ECOLOGICAL OPPORTUNITY (new habitat, empty niches). Followed by rapid diversification.'),
    (['population'],
     'A population = people who could potentially interbreed. Interbreeding group in a location at a time.',
     'Population ≠ species. A species can contain MANY populations with gene flow varying between them.'),
    (['species'],
     'Species = a group that usually makes fertile offspring together, usually not with other groups.',
     'No single species concept works for all life. Use whatever concept fits the question (biological, ecological, phylogenetic).'),
    (['gradualism'],
     'Gradualism = slow, smooth hill-climbing. Many pennies over long time.',
     'Classical Darwinian pace. Contrast with punctuated equilibrium (bursts).'),
    (['punctuated equilibrium'],
     'Long quiet + sudden bursts. Like a band silent for 10 years, then three albums at once.',
     'Eldredge & Gould 1972. Speciation happens FAST in small peripheral populations, then LONG stasis.'),
    (['symbiosis','mutualism'],
     'Bees get nectar, flowers get pollinated — both win. Mutualism = biological double-win.',
     'Mutualism is CONDITIONAL — partners can cheat when ecology shifts.'),
    (['parasitism','parasite'],
     'Tapeworm takes, gives nothing. Parasitism = one wins, one loses. Arms race ensues.',
     'Parasites often drive their host\'s evolution. Endoparasites live IN hosts; ectoparasites live ON them.'),
]

def find_enrichment(q, a):
    text = (q + ' ' + a).lower()
    for keys, analogy, hint in LIB:
        for k in keys:
            if k in text:
                return analogy, hint
    return None, None

matched = 0
for card in data['flashcards']:
    analogy, hint = find_enrichment(card.get('q',''), card.get('a',''))
    if analogy:
        card['analogy'] = analogy
        card['hint'] = hint
        matched += 1
    else:
        # keep any existing analogy if present; add a soft hint prompt
        card.setdefault('analogy', 'Think of an everyday situation that follows the same pattern — concrete examples lock concepts in.')
        card.setdefault('hint', 'Break the term into its Latin/Greek roots — the meaning is often hiding in the word itself.')

# Add c132 cards if missing
existing_ids = {sec['id'] for ch in data['chapters'] for sec in ch.get('sections',[])}
have_c132 = any(c.get('sectionId')=='c132' for c in data['flashcards'])
if 'c132' in existing_ids and not have_c132:
    data['flashcards'].extend([
        {'q':'The three major categories of reproductive isolating mechanisms?',
         'a':'**Prezygotic** (before zygote — ecological, temporal, behavioral, mechanical, gametic) · **Postzygotic** (after zygote — hybrid inviability, hybrid sterility, hybrid breakdown). Prezygotic = never meet or never fertilize. Postzygotic = zygote forms but fails.',
         'chapterId':'ch13','sectionId':'c132','source':'exam3',
         'analogy':'Prezygotic = doorman turns you away at the club. Postzygotic = you get in, order a drink, THEN get kicked out.',
         'hint':'PRE-zygote = BEFORE fertilization · POST-zygote = AFTER. Literal.'},
        {'q':'Prezygotic vs postzygotic — which does selection favor, and why?',
         'a':'**Prezygotic is favored** — no wasted energy on sterile hybrids. When two species start hybridizing, **reinforcement** strengthens prezygotic barriers over time.',
         'chapterId':'ch13','sectionId':'c132','source':'exam3',
         'analogy':'Prezygotic = bouncer filters at the door (cheap). Postzygotic = catered wedding, annulled later (expensive).',
         'hint':'Reinforce-ment = strengthening prezygotic barriers when postzygotic has failed.'},
        {'q':'Behavioral isolation — classic firefly example?',
         'a':'Each species uses a **unique flash pattern**. Females only respond to conspecific males. Wrong code → no mating. Species-specific courtship acts as a prezygotic filter.',
         'chapterId':'ch13','sectionId':'c132','source':'exam3',
         'analogy':'Like Bluetooth pairing PINs — wrong code, no connection. The "network" is species-exclusive.',
         'hint':'Behavioral iso = signals must MATCH. Mismatched ritual → no gametes.'},
    ])

header = '/* auto-generated — Final = Exam1+2+3 + Textbook + Visuals. Every card has analogy + hint. */\nwindow.COURSE = '
open(CF,'w',encoding='utf-8').write(header + json.dumps(data, indent=2, ensure_ascii=False) + ';\n')
print(f"Cards with matched library analogy: {matched}")
print(f"Cards with generic fallback: {len(data['flashcards']) - matched}")
print(f"Total cards now: {len(data['flashcards'])}")
print(f"File size: {os.path.getsize(CF):,} bytes")
